package calculadora2;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gateway
 */

public class TrCalculadora extends javax.swing.JFrame {
    //declaro unas vaiables globales para facilitar las operaciones
    double PrimerNumero;
    double SegundoNumero;
    double Resultado;
    String Operador;
    
    /**
     * Creates new form TrCalculadora
     */
    public TrCalculadora() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pantalla = new javax.swing.JTextField();
        N1 = new javax.swing.JButton();
        N2 = new javax.swing.JButton();
        N3 = new javax.swing.JButton();
        N4 = new javax.swing.JButton();
        N9 = new javax.swing.JButton();
        N0 = new javax.swing.JButton();
        Suma = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        N5 = new javax.swing.JButton();
        N6 = new javax.swing.JButton();
        N7 = new javax.swing.JButton();
        N8 = new javax.swing.JButton();
        Division = new javax.swing.JButton();
        Multiplicacion = new javax.swing.JButton();
        Punto = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(315, 455));
        setResizable(false);
        getContentPane().setLayout(null);

        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(pantalla);
        pantalla.setBounds(30, 40, 240, 60);

        N1.setBackground(new java.awt.Color(230, 200, 255));
        N1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N1.setText("1");
        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        getContentPane().add(N1);
        N1.setBounds(30, 150, 60, 50);

        N2.setBackground(new java.awt.Color(230, 200, 255));
        N2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N2.setText("2");
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        getContentPane().add(N2);
        N2.setBounds(100, 150, 60, 50);

        N3.setBackground(new java.awt.Color(230, 200, 255));
        N3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N3.setText("3");
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        getContentPane().add(N3);
        N3.setBounds(170, 150, 60, 50);

        N4.setBackground(new java.awt.Color(230, 200, 255));
        N4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N4.setText("4");
        N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N4ActionPerformed(evt);
            }
        });
        getContentPane().add(N4);
        N4.setBounds(30, 210, 60, 50);

        N9.setBackground(new java.awt.Color(230, 200, 255));
        N9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N9.setText("9");
        N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N9ActionPerformed(evt);
            }
        });
        getContentPane().add(N9);
        N9.setBounds(170, 270, 60, 50);

        N0.setBackground(new java.awt.Color(230, 200, 255));
        N0.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N0.setText("0");
        N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0ActionPerformed(evt);
            }
        });
        getContentPane().add(N0);
        N0.setBounds(30, 330, 60, 50);

        Suma.setBackground(new java.awt.Color(230, 158, 196));
        Suma.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Suma.setText("+");
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });
        getContentPane().add(Suma);
        Suma.setBounds(240, 260, 40, 20);

        Resta.setBackground(new java.awt.Color(230, 158, 196));
        Resta.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Resta.setText("-");
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });
        getContentPane().add(Resta);
        Resta.setBounds(240, 290, 40, 30);

        N5.setBackground(new java.awt.Color(230, 200, 255));
        N5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N5.setText("5");
        N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N5ActionPerformed(evt);
            }
        });
        getContentPane().add(N5);
        N5.setBounds(100, 210, 60, 50);

        N6.setBackground(new java.awt.Color(230, 200, 255));
        N6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N6.setText("6");
        N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N6ActionPerformed(evt);
            }
        });
        getContentPane().add(N6);
        N6.setBounds(170, 210, 60, 50);

        N7.setBackground(new java.awt.Color(230, 200, 255));
        N7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N7.setText("7");
        N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N7ActionPerformed(evt);
            }
        });
        getContentPane().add(N7);
        N7.setBounds(30, 270, 60, 50);

        N8.setBackground(new java.awt.Color(230, 200, 255));
        N8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N8.setText("8");
        N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N8ActionPerformed(evt);
            }
        });
        getContentPane().add(N8);
        N8.setBounds(100, 270, 60, 50);

        Division.setBackground(new java.awt.Color(230, 158, 196));
        Division.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Division.setText("/");
        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });
        getContentPane().add(Division);
        Division.setBounds(240, 197, 40, 25);

        Multiplicacion.setBackground(new java.awt.Color(230, 158, 196));
        Multiplicacion.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Multiplicacion.setText("*");
        Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(Multiplicacion);
        Multiplicacion.setBounds(240, 230, 40, 20);

        Punto.setBackground(new java.awt.Color(230, 158, 196));
        Punto.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Punto.setText(".");
        Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntoActionPerformed(evt);
            }
        });
        getContentPane().add(Punto);
        Punto.setBounds(100, 330, 50, 50);

        Igual.setBackground(new java.awt.Color(230, 158, 196));
        Igual.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Igual.setText("=");
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });
        getContentPane().add(Igual);
        Igual.setBounds(160, 330, 120, 50);

        Borrar.setBackground(new java.awt.Color(255, 51, 51));
        Borrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Borrar.setText("C");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        getContentPane().add(Borrar);
        Borrar.setBounds(240, 150, 40, 40);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 340, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
        // ahora las dos lineas de codigo las aplico para todos los numeros
    String Numero = pantalla.getText()+N1.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver
    pantalla.setText(Numero);
    }//GEN-LAST:event_N1ActionPerformed

    private void N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0ActionPerformed
        // pide que traiga lo que esta en el text field y el valor de cundo apetemos 0
    String Numero = pantalla.getText()+N0.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver
    pantalla.setText(Numero);
    }//GEN-LAST:event_N0ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed

    String Numero = pantalla.getText()+N2.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver
    pantalla.setText(Numero);
    }//GEN-LAST:event_N2ActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
    
    String Numero = pantalla.getText()+N3.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver y sumar coresctamente
    pantalla.setText(Numero);
    }//GEN-LAST:event_N3ActionPerformed

    private void N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N4ActionPerformed
      
    String Numero = pantalla.getText()+N4.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver y sumar coresctamente
    pantalla.setText(Numero);
    }//GEN-LAST:event_N4ActionPerformed

    private void N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N5ActionPerformed
       
    String Numero = pantalla.getText()+N5.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver y sumar coresctamente
    pantalla.setText(Numero);
    }//GEN-LAST:event_N5ActionPerformed

    private void N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N6ActionPerformed
       
    String Numero = pantalla.getText()+N6.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver y sumar coresctamente
    pantalla.setText(Numero);
    }//GEN-LAST:event_N6ActionPerformed

    private void N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N7ActionPerformed
     
    String Numero = pantalla.getText()+N7.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver y sumar coresctamente
    pantalla.setText(Numero);
    }//GEN-LAST:event_N7ActionPerformed

    private void N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N8ActionPerformed
      
    String Numero = pantalla.getText()+N8.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver y sumar coresctamente
    pantalla.setText(Numero);
    }//GEN-LAST:event_N8ActionPerformed

    private void N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N9ActionPerformed
       
    String Numero = pantalla.getText()+N9.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver y sumar coresctamente
    pantalla.setText(Numero);
    }//GEN-LAST:event_N9ActionPerformed

    private void PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntoActionPerformed
    String Numero = pantalla.getText()+Punto.getText();
    //esta linea es para cuando escribamos el 0 se pueda ver y sumar coresctamente
    pantalla.setText(Numero);
    }//GEN-LAST:event_PuntoActionPerformed

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
        // ahora es solo copiar el codigo de la suma y cambiar los operadores
     PrimerNumero = Double.parseDouble(pantalla.getText());
    pantalla.setText(" ");
    Operador="-";
   
    }//GEN-LAST:event_RestaActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // Este es el boton c, que elimina todo de la pantalla
     pantalla.setText(" ");
    }//GEN-LAST:event_BorrarActionPerformed

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        //esta parte es donde se realiza la suma
    PrimerNumero = Double.parseDouble(pantalla.getText());
    pantalla.setText(" ");
    Operador="+";
    }//GEN-LAST:event_SumaActionPerformed

    private void MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionActionPerformed
     PrimerNumero = Double.parseDouble(pantalla.getText());
    pantalla.setText(" ");
    Operador="*";
    }//GEN-LAST:event_MultiplicacionActionPerformed

    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionActionPerformed
    PrimerNumero = Double.parseDouble(pantalla.getText());
    pantalla.setText(" ");
    Operador="/";
    }//GEN-LAST:event_DivisionActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
    SegundoNumero = Double.parseDouble(pantalla.getText());
    
    if(Operador.equals("+")){
        Resultado = PrimerNumero + SegundoNumero;
        pantalla.setText(Double.toString(Resultado));  
    }else if (Operador.equals("-")){
        Resultado = PrimerNumero - SegundoNumero;
        pantalla.setText(Double.toString(Resultado));  
        
    }else if (Operador.equals("*")){
        Resultado = PrimerNumero * SegundoNumero;
        pantalla.setText(Double.toString(Resultado));
        
    }else if (Operador.equals("/")){
        Resultado = PrimerNumero / SegundoNumero;
        pantalla.setText(Double.toString(Resultado));  
    } 
    }//GEN-LAST:event_IgualActionPerformed
    
    public static void main(String[]args){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Division;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Multiplicacion;
    private javax.swing.JButton N0;
    private javax.swing.JButton N1;
    private javax.swing.JButton N2;
    private javax.swing.JButton N3;
    private javax.swing.JButton N4;
    private javax.swing.JButton N5;
    private javax.swing.JButton N6;
    private javax.swing.JButton N7;
    private javax.swing.JButton N8;
    private javax.swing.JButton N9;
    private javax.swing.JButton Punto;
    private javax.swing.JButton Resta;
    private javax.swing.JButton Suma;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pantalla;
    // End of variables declaration//GEN-END:variables
}

